### PR TITLE
update deps

### PR DESCRIPTION
**Pull request by sibelius**

### CODE REVIEW

**Comment by lucasbento** [comment]
I guess @greenkeeperio doesn't work well with Lerna projects :(

**Comment by sibelius** [comment]
testing working fine locally on node 6.9.1

should we upgrade node version on CI?

**Comment by lucasbento** [comment]
Yeah, we can do that.

But it should run fine on 4.4.7 too.

For reference about @greenkeeperio: https://github.com/greenkeeperio/greenkeeper/issues/139.

**Comment by lucasbento** [comment]
Jest parallelism doesn't seem to go well with CI, adding `--runInBand` (to run sequentially) fixed it.

**Comment by sibelius** [comment]
Great, we just need to upgrade yeoman to 1.0 later on

**Pull request merged**
