### PR TITLE
add viewer to mutationadd

### LINKED ISSUE #37: Return `viewer` on MutationAdd template

### PR DESCRIPTION
**Pull request by sibelius**
fix #37

### CODE REVIEW

**Comment by rturk** [comment]
This will always include a `viewer` in the mutation?

**Comment by sibelius** [comment]
only on add mutation, we can move this as a parameter or as a config later

**Comment by lucasbento** [comment]
@sibelius: The boilerplate has a [`ViewerLoader`](https://github.com/entria/graphql-dataloader-boilerplate/blob/master/src/loader/ViewerLoader.js), should we use it or not?

**Comment by sibelius** [comment]
neh, just return the logged user

**Pull request merged**
